"""Initial migration

Revision ID: 874b7b402569
Revises: 
Create Date: 2025-12-28 05:54:41.892343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '874b7b402569'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('code', sa.String(length=20), nullable=False, comment='ISTAT country code (e.g., 100000100 for Italy)'),
    sa.Column('name_it', sa.String(length=255), nullable=False, comment='Country name in Italian (e.g., Italia)'),
    sa.Column('name_en', sa.String(length=255), nullable=False, comment='Country name in English (e.g., Italy)'),
    sa.Column('iso_code', sa.String(length=2), nullable=True, comment='ISO 3166-1 alpha-2 code (e.g., IT)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_countries'))
    )
    op.create_index('ix_country_name_en', 'countries', ['name_en'], unique=False)
    op.create_index('ix_country_name_it', 'countries', ['name_it'], unique=False)
    op.create_table('municipalities',
    sa.Column('code', sa.String(length=10), nullable=False, comment='ISTAT Codice Catastale (e.g., H810)'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Municipality name (e.g., Schilpario)'),
    sa.Column('province_code', sa.String(length=2), nullable=False, comment='Province code (e.g., BG for Bergamo)'),
    sa.Column('province_name', sa.String(length=100), nullable=False, comment='Province full name (e.g., Bergamo)'),
    sa.Column('region', sa.String(length=100), nullable=False, comment='Region name (e.g., Lombardia)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_municipalities'))
    )
    op.create_index('ix_municipality_name', 'municipalities', ['name'], unique=False)
    op.create_index('ix_municipality_province', 'municipalities', ['province_code'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('facility_code', sa.String(length=50), nullable=False, comment='Codice Struttura (CIR) assigned by Lombardy Region'),
    sa.Column('ros1000_username', sa.String(length=255), nullable=True),
    sa.Column('ros1000_password', sa.String(length=255), nullable=True),
    sa.Column('ros1000_ws_key', sa.String(length=500), nullable=True, comment='Web Service Key for Questura bridge (from Alloggiati Web)'),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants')),
    sa.UniqueConstraint('facility_code', name=op.f('uq_tenants_facility_code'))
    )
    op.create_table('bookings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('booking_type', sa.Enum('INDIVIDUAL', 'FAMILY', 'GROUP', name='bookingtype', native_enum=False), nullable=False),
    sa.Column('check_in_date', sa.Date(), nullable=False),
    sa.Column('check_out_date', sa.Date(), nullable=False),
    sa.Column('expected_guests', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETE', 'SYNCED', 'ERROR', name='bookingstatus', native_enum=False), nullable=False),
    sa.Column('magic_link_token', sa.String(length=100), nullable=False, comment='Cryptographically secure token for guest portal access'),
    sa.Column('token_expires_at', sa.DateTime(), nullable=False, comment='Token expires on check-out date for security'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ros1000_receipt_number', sa.String(length=100), nullable=True, comment='ROS1000 receipt number from successful submission'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_bookings_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookings'))
    )
    op.create_index(op.f('ix_bookings_magic_link_token'), 'bookings', ['magic_link_token'], unique=True)
    op.create_index(op.f('ix_bookings_tenant_id'), 'bookings', ['tenant_id'], unique=False)
    op.create_table('tax_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False, comment='Start date for this tax rule'),
    sa.Column('valid_until', sa.Date(), nullable=True, comment='End date (NULL = currently active)'),
    sa.Column('base_rate_per_night', sa.Numeric(precision=10, scale=2), nullable=False, comment='Tax rate per night in EUR (e.g., 1.00)'),
    sa.Column('max_taxable_nights', sa.Integer(), nullable=True, comment='Cap on taxable nights (e.g., 10 = only first 10 nights taxed)'),
    sa.Column('age_exemption_threshold', sa.Integer(), nullable=True, comment='Age below which guests are exempt (e.g., 14 years)'),
    sa.Column('exemption_rules', sa.JSON(), nullable=False, comment="JSON config for role exemptions (e.g., {'bus_driver_ratio': 25})"),
    sa.Column('structure_classification', sa.String(length=50), nullable=True, comment="Hotel classification affecting rate (e.g., '3-star', 'hostel')"),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tax_rules_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tax_rules'))
    )
    op.create_index(op.f('ix_tax_rules_tenant_id'), 'tax_rules', ['tenant_id'], unique=False)
    op.create_table('compliance_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('submission_type', sa.String(length=50), nullable=False, comment='Type of submission (ROS1000, CANCELLATION, etc.)'),
    sa.Column('submitted_at', sa.DateTime(), nullable=False, comment='When the submission was made'),
    sa.Column('status', sa.Enum('SUBMITTED', 'FAILED', 'CANCELLED', 'SUCCESS', 'PARTIAL_SUCCESS', 'FAILURE', name='compliancestatus', native_enum=False), nullable=False),
    sa.Column('receipt_number', sa.String(length=100), nullable=True, comment='Receipt number (numeroRicevuta) returned by ROS1000'),
    sa.Column('ros1000_protocol_id', sa.String(length=100), nullable=True, comment='Protocol ID returned by ROS1000 on success'),
    sa.Column('police_receipt_code', sa.String(length=100), nullable=True, comment='Police receipt code from Questura/Alloggiati Web'),
    sa.Column('xml_payload', sa.Text(), nullable=False, comment='Full XML payload sent to ROS1000'),
    sa.Column('request_xml', sa.Text(), nullable=True, comment='Full XML SOAP request envelope (optional)'),
    sa.Column('response_xml', sa.Text(), nullable=True, comment='Full XML SOAP response from ROS1000'),
    sa.Column('response_data', sa.JSON(), nullable=True, comment='Parsed response data as JSON'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error details for partial success or failure cases'),
    sa.Column('error_details', sa.JSON(), nullable=True, comment='Structured error data (e.g., which guests failed validation)'),
    sa.Column('retry_count', sa.Integer(), nullable=False, comment='Number of retry attempts'),
    sa.Column('last_retry_at', sa.DateTime(), nullable=True, comment='Timestamp of last retry attempt'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_compliance_records_booking_id_bookings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_records'))
    )
    op.create_index(op.f('ix_compliance_records_booking_id'), 'compliance_records', ['booking_id'], unique=False)
    op.create_table('guests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('LEADER', 'MEMBER', 'BUS_DRIVER', 'TOUR_GUIDE', name='guestrole', native_enum=False), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('sex', sa.Enum('MALE', 'FEMALE', name='sex', native_enum=False), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('place_of_birth_municipality_code', sa.String(length=10), nullable=True, comment='ISTAT Codice Catastale (e.g., H810 for Schilpario)'),
    sa.Column('place_of_birth_country_code', sa.String(length=20), nullable=True, comment='ISTAT country code (e.g., 100000100 for Italy)'),
    sa.Column('residence_municipality_code', sa.String(length=10), nullable=True, comment='ISTAT Codice Catastale'),
    sa.Column('residence_country_code', sa.String(length=20), nullable=True, comment='ISTAT country code'),
    sa.Column('residence_address', sa.String(length=255), nullable=True),
    sa.Column('residence_zip_code', sa.String(length=20), nullable=True),
    sa.Column('document_type', sa.Enum('PASSPORT', 'ID_CARD', 'DRIVING_LICENSE', 'OTHER', name='documenttype', native_enum=False), nullable=True),
    sa.Column('document_number', sa.String(length=50), nullable=True),
    sa.Column('document_issuing_authority', sa.String(length=255), nullable=True),
    sa.Column('document_issue_date', sa.Date(), nullable=True),
    sa.Column('document_issue_place', sa.String(length=255), nullable=True),
    sa.Column('is_tax_exempt', sa.Boolean(), nullable=False, comment='Exempt from City Tax (minor, driver, guide)'),
    sa.Column('tax_exemption_reason', sa.String(length=100), nullable=True, comment='Reason for exemption (age, bus_driver, tour_guide)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_guests_booking_id_bookings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guests'))
    )
    op.create_index(op.f('ix_guests_booking_id'), 'guests', ['booking_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guests_booking_id'), table_name='guests')
    op.drop_table('guests')
    op.drop_index(op.f('ix_compliance_records_booking_id'), table_name='compliance_records')
    op.drop_table('compliance_records')
    op.drop_index(op.f('ix_tax_rules_tenant_id'), table_name='tax_rules')
    op.drop_table('tax_rules')
    op.drop_index(op.f('ix_bookings_tenant_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_magic_link_token'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_table('tenants')
    op.drop_index('ix_municipality_province', table_name='municipalities')
    op.drop_index('ix_municipality_name', table_name='municipalities')
    op.drop_table('municipalities')
    op.drop_index('ix_country_name_it', table_name='countries')
    op.drop_index('ix_country_name_en', table_name='countries')
    op.drop_table('countries')
    # ### end Alembic commands ###
